import type { Plugin } from './types'

// Auto-generated by update-plugins.js
// Do not edit manually - changes will be overwritten

export const plugins: Plugin[] = [
  {
    name: 'jira-issue',
    version: '1.1.0',
    description: 'Jira 이슈 조회 스킬. PR 리뷰 시 관련 이슈를 자동으로 확인하고, 티켓 상세 정보를 조회할 수 있습니다. 댓글 작성 기능도 지원합니다.',
    category: 'development',
    keywords: ["공통","skill","jira","pr-review"],
    author: {
      name: 'WhaTap Labs',
      email: 'dev@whatap.io',
    },
    homepage: 'https://github.com/whatap/claude-plugins/tree/main/plugins/jira-issue',
    repository: 'https://github.com/whatap/claude-plugins',
    license: 'MIT',
    platform: ["macOS","Linux","Windows"],
    readme: `# Jira Issue Viewer

Jira 이슈 정보를 조회하는 Claude Code 스킬입니다.

## Features

- Jira 이슈 상세 정보 조회
- PR 리뷰 시 관련 이슈 빠른 확인
- 컬러 출력으로 가독성 향상

## Prerequisites

- **jq**: JSON 파싱용
- **curl**: API 호출용
- **Jira API Token**: Atlassian 계정의 API 토큰

## Installation

Claude Code에서 플러그인을 설치하면 자동으로 \`/jira-issue\` 스킬을 사용할 수 있습니다.

## Environment Variables

다음 환경변수를 설정해야 합니다:

\`\`\`bash
# 필수
export JIRA_EMAIL="your-email@whatap.io"
export JIRA_API_TOKEN="your-api-token"

# 선택 (기본값: https://whatap-labs.atlassian.net)
export JIRA_BASE_URL="https://your-domain.atlassian.net"
\`\`\`

### API 토큰 발급 방법

1. [Atlassian API Token 관리](https://id.atlassian.com/manage-profile/security/api-tokens) 페이지 접속
2. "Create API token" 클릭
3. 토큰 이름 입력 후 생성
4. 생성된 토큰을 \`JIRA_API_TOKEN\` 환경변수에 설정

## Usage

Claude Code에서 다음과 같이 사용합니다:

\`\`\`
/jira-issue SERVER-1448
\`\`\`

### 출력 예시

\`\`\`
══════════════════════════════════════════════════════════════
[SERVER-1448] 메트릭 수집 성능 개선
══════════════════════════════════════════════════════════════

타입:      Task
상태:      In Progress
우선순위:  High
담당자:    홍길동
보고자:    김철수
라벨:      performance, backend
생성일:    2024-01-15
수정일:    2024-01-20

── 설명 ──────────────────────────────────────────────────────
메트릭 수집 시 병목 현상 발생. 배치 처리 방식으로 변경 필요.

══════════════════════════════════════════════════════════════
URL: https://whatap-labs.atlassian.net/browse/SERVER-1448
\`\`\`

## Use Cases

1. **PR 리뷰 시**: 커밋 메시지나 PR 제목의 티켓 번호로 이슈 내용 확인
2. **작업 시작 전**: 할당된 이슈의 상세 요구사항 확인
3. **코드 리뷰 시**: 변경 사항이 이슈 요구사항과 일치하는지 검증

## License

MIT
`,
  },
  {
    name: 'notification-hook',
    version: '1.0.0',
    description: '작업 완료/입력 대기 시 macOS 데스크톱 알림을 제공합니다. Claude Code가 오래 걸리는 작업을 완료하거나 사용자 입력이 필요할 때 알림을 받을 수 있습니다.',
    category: 'productivity',
    keywords: ["공통","hook","notification","macos"],
    author: {
      name: 'WhaTap Labs',
      email: 'dev@whatap.io',
    },
    homepage: 'https://github.com/whatap/claude-plugins/tree/main/plugins/notification-hook',
    repository: 'https://github.com/whatap/claude-plugins',
    license: 'MIT',
    platform: ["macOS"],
    readme: `# notification-hook

Claude Code 작업 완료/입력 대기 시 macOS 데스크톱 알림을 보내는 Hook 플러그인

## 기능

| Hook | 이벤트 | 설명 |
|------|--------|------|
| Notification | idle_prompt | 입력 대기 시 알림 |
| Notification | permission_prompt | 권한 요청 시 알림 |
| Stop | - | 작업 완료 시 알림 |
| PostToolUse | Bash (30초+) | 장시간 명령 완료 시 알림 |

## 요구사항

- macOS
- jq (\`brew install jq\`)
- terminal-notifier (권장, \`brew install terminal-notifier\`)

## 설치

### 마켓플레이스에서 설치
\`\`\`bash
# 마켓플레이스 추가
/plugin marketplace add whatap/claude-plugins

# 플러그인 설치
/plugin install notification-hook@whatap-claude-plugins
\`\`\`

### 수동 설치
\`\`\`bash
# 1. 스크립트 복사
mkdir -p ~/.claude/hooks
cp scripts/*.sh ~/.claude/hooks/
chmod +x ~/.claude/hooks/*.sh

# 2. settings.json에 Hook 추가
# ~/.claude/settings.json 또는 .claude/settings.json
\`\`\`

## 설정 예시

\`\`\`json
{
  "hooks": {
    "Notification": [
      {
        "matcher": "",
        "hooks": [
          {
            "type": "command",
            "command": "~/.claude/hooks/notify.sh"
          }
        ]
      }
    ],
    "Stop": [
      {
        "hooks": [
          {
            "type": "command",
            "command": "~/.claude/hooks/notify-stop.sh"
          }
        ]
      }
    ]
  }
}
\`\`\`

## 태그

- 공통
- hook
- notification
- macos

## 라이선스

MIT
`,
  },
  {
    name: 'skill-authoring-review',
    version: '1.1.1',
    description: 'Claude Code 스킬 작성 및 검증 도구. 새로운 스킬 초기화, 기존 스킬 검증, Anthropic 공식 가이드라인 준수 여부 확인을 지원합니다.',
    category: 'development',
    keywords: ["공통","skill","개발도구","검증"],
    author: {
      name: 'WhaTap Labs',
      email: 'dev@whatap.io',
    },
    homepage: 'https://github.com/whatap/claude-plugins/tree/main/plugins/skill-authoring-review',
    repository: 'https://github.com/whatap/claude-plugins',
    license: 'MIT',
    platform: ["macOS","Linux","Windows"],
    readme: `# Skill Authoring & Review

Claude Code 스킬 작성 및 검증 도구입니다. Anthropic 공식 가이드라인을 기반으로 합니다.

## Features

- 새로운 스킬 초기화 (디렉토리 구조 + 템플릿)
- 기존 스킬 검증 (구조, frontmatter, 스타일)
- 일괄 검증 지원 (recursive)
- 다양한 출력 형식 (text, json, markdown)

## Prerequisites

- **Python 3.9+**: 검증 스크립트 실행용
- **Bash**: 초기화 스크립트 실행용

## Installation

Claude Code에서 플러그인을 설치하면 자동으로 스킬을 사용할 수 있습니다.

## Usage

### 새 스킬 생성

\`\`\`bash
# 기본 사용법
~/.claude/skills/skill-authoring-review/scripts/init_skill.sh <skill-name> <output-directory>

# 예시
~/.claude/skills/skill-authoring-review/scripts/init_skill.sh pdf-editor ~/.claude/skills
\`\`\`

생성되는 구조:
\`\`\`
<skill-name>/
├── SKILL.md          # 메인 스킬 문서 (편집 필요)
├── scripts/          # 실행 스크립트
│   └── example.sh
├── references/       # 참조 문서
│   └── documentation.md
└── assets/           # 출력 파일용 리소스
\`\`\`

### 스킬 검증

\`\`\`bash
# 단일 스킬 검증
python3 ~/.claude/skills/skill-authoring-review/scripts/validate_skill.py ~/.claude/skills/my-skill

# 전체 스킬 검증 (재귀)
python3 ~/.claude/skills/skill-authoring-review/scripts/validate_skill.py ~/.claude/skills --recursive

# JSON 출력
python3 ~/.claude/skills/skill-authoring-review/scripts/validate_skill.py ~/.claude/skills --format json

# Markdown 리포트
python3 ~/.claude/skills/skill-authoring-review/scripts/validate_skill.py ~/.claude/skills --format markdown
\`\`\`

### 출력 예시

\`\`\`
============================================================
Skill: my-skill
Path: /Users/user/.claude/skills/my-skill
Words: 1234
Valid: Yes
============================================================

  WARNINGS:
    - [body] Found 3 second-person usage(s)
      Suggestion: Use imperative/infinitive form. Examples: L45: 'You can configure...'

  SUGGESTIONS:
    - [progressive_disclosure] SKILL.md is 1234 words (recommended: 1,500-2,000)
      Suggestion: Consider splitting into references/ if content grows
\`\`\`

## Validation Rules

### Critical (필수 수정)
- \`SKILL.md\` 파일 존재 (대문자)
- frontmatter의 \`name\` 필드
- frontmatter의 \`description\` 필드

### Warning (권장 수정)
- 디렉토리 이름과 \`name\` 필드 일치
- description 3인칭 작성
- body에서 2인칭 사용 금지 (you, your)

### Suggestion (개선 권장)
- 적정 분량: 1,500-2,000 words
- 트리거 조건 명시

## Skill Guidelines Summary

### Frontmatter 예시

\`\`\`yaml
---
name: my-skill
description: Brief description in third-person. This skill should be used when [conditions]. Triggers on requests like "[phrases]".
---
\`\`\`

### 작성 스타일

**올바른 예:**
\`\`\`markdown
To rotate a PDF, run the following command:
\`\`\`

**잘못된 예:**
\`\`\`markdown
You can rotate a PDF by running:
\`\`\`

## References

- \`references/anthropic-skill-guide.md\` - Anthropic 공식 가이드라인 요약
- \`references/validation-checklist.md\` - 상세 검증 체크리스트
- \`references/templates.md\` - 스킬 유형별 템플릿
- \`assets/minimal-skill.md\` - 최소 유효 스킬 예시

## License

MIT
`,
  },
  {
    name: 'usage-statusbar',
    version: '1.0.0',
    description: 'Context Window와 5시간 블록 사용량을 이모지 막대 그래프로 표시하는 statusline 플러그인입니다. 실시간으로 사용량과 리셋 시간을 확인할 수 있습니다.',
    category: 'productivity',
    keywords: ["공통","statusline","usage","context"],
    author: {
      name: 'WhaTap Labs',
      email: 'dev@whatap.io',
    },
    homepage: 'https://github.com/whatap/claude-plugins/tree/main/plugins/usage-statusbar',
    repository: 'https://github.com/whatap/claude-plugins',
    license: 'MIT',
    platform: ["macOS"],
    readme: `# usage-statusbar

Claude Code statusline 플러그인으로 Context Window와 5시간 블록 사용량을 이모지 막대 그래프로 표시합니다.

## 출력 예시

\`\`\`
🧠 🟩🟩🟩🟩🟩⬜⬜⬜⬜⬜ 46% | ⏰ 🟩⬜⬜⬜⬜⬜⬜⬜⬜⬜ 8% | Reset: 4h 49m
\`\`\`

## 기능

| 항목 | 설명 | 데이터 소스 |
|------|------|------------|
| 🧠 Context | 현재 컨텍스트 윈도우 사용량 | stdin JSON (\`used_percentage\`) |
| ⏰ Block | 5시간 블록 사용량 | Anthropic API (\`utilization\`) |
| Reset | 블록 리셋까지 남은 시간 | Anthropic API (\`resets_at\`) |

## 색상 구간

| 범위 | 색상 |
|------|------|
| 0-50% | 🟩 녹색 |
| 51-80% | 🟨 노란색 |
| 81-100% | 🟥 빨간색 |
| 빈 칸 | ⬜ 흰색 |

## 설치

### 1. 의존성 설치 및 빌드

\`\`\`bash
cd plugins/usage-statusbar
bun install
bun run build
\`\`\`

### 2. settings.json 설정

\`\`\`json
{
  "statusLine": {
    "type": "command",
    "command": "bun /path/to/plugins/usage-statusbar/dist/index.js",
    "padding": 0
  }
}
\`\`\`

## 요구사항

- **Bun**: TypeScript 런타임
- **macOS**: Keychain에서 Claude Code credential 접근 필요
- **Claude Code 로그인**: OAuth 인증 필요

## 작동 방식

1. stdin에서 Claude Code가 전달하는 JSON 읽기 (context window 정보)
2. macOS Keychain에서 Claude Code OAuth 토큰 가져오기
3. Anthropic API (\`/api/oauth/usage\`) 호출하여 5시간 블록 정보 조회
4. 이모지 막대 그래프로 렌더링하여 stdout 출력

## API 응답 예시

\`\`\`json
{
  "five_hour": {
    "utilization": 8.0,
    "resets_at": "2026-02-04T05:59:59.564221+00:00"
  },
  "seven_day": {
    "utilization": 53.0,
    "resets_at": "2026-02-05T09:59:59.564247+00:00"
  }
}
\`\`\`

## 라이선스

MIT
`,
  }
]

export function getPluginByName(name: string): Plugin | undefined {
  return plugins.find((p) => p.name === name)
}

export function searchPlugins(query: string, category?: string, tags?: string[]): Plugin[] {
  return plugins.filter((plugin) => {
    // Search query
    if (query) {
      const q = query.toLowerCase()
      const matchesQuery =
        plugin.name.toLowerCase().includes(q) ||
        plugin.description.toLowerCase().includes(q) ||
        plugin.keywords.some((k) => k.toLowerCase().includes(q))
      if (!matchesQuery) return false
    }

    // Category filter
    if (category && category !== 'all' && plugin.category !== category) {
      return false
    }

    // Tags filter
    if (tags && tags.length > 0) {
      const hasTag = tags.some((tag) =>
        plugin.keywords.some((k) => k.toLowerCase() === tag.toLowerCase())
      )
      if (!hasTag) return false
    }

    return true
  })
}
