import type { Plugin } from './types'

// Auto-generated by update-plugins.js
// Do not edit manually - changes will be overwritten

export const plugins: Plugin[] = [
  {
    name: 'book-purchase',
    version: '1.0.0',
    description: '알라딘 도서 검색 + Slack #books 구매 신청 자동화 (/도서구매)',
    category: 'productivity',
    keywords: ["공통","skill","도서","구매","알라딘","slack"],
    author: {
      name: 'WhaTap Labs',
      email: 'dev@whatap.io',
    },
    homepage: 'https://github.com/whatap/claude-plugins/tree/main/plugins/book-purchase',
    repository: 'https://github.com/whatap/claude-plugins',
    license: 'MIT',
    platform: ["macOS"],
    readme: `# book-purchase

알라딘 도서 검색 및 구매 신청 스킬. Slack #books 채널에서 \`/도서구매\` 슬래시 커맨드를 CDP로 실행합니다.

## 기능

- 도서명으로 알라딘 검색
- 알라딘 URL에서 도서 정보 추출 (제목/저자/출판사/가격/절판 여부)
- Slack \`/도서구매\` 슬래시 커맨드 자동 실행 (CDP)

## 사용법

\`\`\`
/도서구매 <알라딘-URL>
/도서구매 <도서명>
\`\`\`

## 의존성

- \`slack-cdp\` 플러그인 (CDP 인프라)
- Python 3 (표준 라이브러리만 사용)

## 스크립트

| 스크립트 | 용도 |
|----------|------|
| \`search-book.py\` | 알라딘 도서 검색, 정형화 출력 |
| \`fetch-book.py\` | URL에서 도서 상세 정보 추출 |
`,
  },
  {
    name: 'cal',
    version: '1.0.0',
    description: 'MCP 기반 Google Calendar 통합 - 환경변수 없이 OAuth로 일정 조회/생성/수정/빈 시간 확인',
    category: 'productivity',
    keywords: ["공통","skill","calendar","mcp","google"],
    author: {
      name: 'WhaTap Labs',
      email: 'dev@whatap.io',
    },
    homepage: 'https://github.com/whatap/claude-plugins/tree/main/plugins/cal',
    repository: 'https://github.com/whatap/claude-plugins',
    license: 'MIT',
    platform: ["macOS","Linux","Windows"],
    readme: `# Google Calendar MCP 통합 스킬

MCP(Google Calendar OAuth)를 통한 캘린더 통합 스킬입니다. 환경변수 설정 없이 바로 사용 가능합니다.

## Features

- \`/cal\` 또는 \`/cal today\` - 오늘 일정 조회
- \`/cal tomorrow\` - 내일 일정
- \`/cal week\` - 이번 주 일정 (요일별 그룹핑)
- \`/cal next week\` - 다음 주 일정
- \`/cal YYYY-MM-DD\` - 특정 날짜 일정
- \`/cal free\` - 오늘 빈 시간 조회 (업무 시간 09:00~18:00)
- \`/cal free tomorrow\` - 내일 빈 시간
- \`/cal search 쿼리\` - 일정 검색
- \`/cal new\` - 일정 생성 (대화형)
- \`/cal respond EVENT_ID accept/decline/tentative\` - 일정 응답

## Prerequisites

- Claude Code에 **Google Calendar MCP 연동**이 설정되어 있어야 합니다
- Node.js나 환경변수 설정은 불필요

## Installation

\`\`\`
/plugin install cal@whatap-claude-plugins
\`\`\`

## Usage

### 오늘 일정

\`\`\`
/cal
/cal today
\`\`\`

### 이번 주 일정

\`\`\`
/cal week
\`\`\`

### 빈 시간 확인

\`\`\`
/cal free
/cal free tomorrow
/cal free 2026-03-01
\`\`\`

### 일정 검색

\`\`\`
/cal search 스탠드업
/cal search 인터뷰
\`\`\`

### 일정 생성

\`\`\`
/cal new
\`\`\`

대화형으로 제목, 날짜, 시간, 참석자, 장소, Google Meet 여부를 입력받습니다.

### 일정 응답

\`\`\`
/cal respond EVENT_ID accept
/cal respond EVENT_ID decline
/cal respond EVENT_ID tentative
\`\`\`

## 출력 형식

일정은 타임라인 테이블 형식으로 표시됩니다:

| 시간 | 일정 | 장소 | 참석자 |
|------|------|------|--------|
| 09:00-10:00 | 팀 스탠드업 | Google Meet | 5명 |
| 14:00-15:00 | 1:1 미팅 | 회의실 A | 2명 |

## 주의사항

- 모든 시간은 **Asia/Seoul (KST, UTC+9)** 기준
- 일정 삭제는 확인 프롬프트 후 실행
- 일정 생성/수정 시 참석자에게 알림이 발송됨

## Changelog

### v1.0.0

- 초기 릴리스
- 일정 조회 (오늘, 내일, 주간, 특정 날짜)
- 빈 시간 조회
- 일정 검색, 생성, 응답

## License

MIT
`,
  },
  {
    name: 'docs-writing',
    version: '1.0.0',
    description: '테크니컬 라이터(TW) 관점의 문서 개선 스킬. WhaTap Docs 초안을 자동 생성하고, 기술 문서 품질을 높여줍니다.',
    category: 'development',
    keywords: ["공통","skill","docs","기술문서"],
    author: {
      name: '박수빈',
      email: 'dev@whatap.io',
    },
    homepage: 'https://github.com/whatap/claude-plugins/tree/main/plugins/docs-writing',
    repository: 'https://github.com/whatap/claude-plugins',
    license: 'MIT',
    platform: ["macOS","Linux","Windows"],
    readme: `# Docs Writing

테크니컬 라이터(TW) 관점에서 기술 문서를 개선하는 Claude Code 스킬입니다.

개발자가 전달한 기능 설명·자료를 바탕으로 WhaTap Docs에 올릴 사용자 가이드 초안을 자동 생성합니다.

> ⚠️ **최종 배포 전 TW 검토 필수** (초안 생성 도구)

## Features

- 문서 목적·구조 정리
- UI 표기 규칙 자동 적용
- 사용자 관점 문장으로 초안 생성
- 부족한 자료는 \`[데모 링크 필요]\`, \`[화면 공유 필요]\`로 표시

## Usage

### 초안 작성 모드

개발자가 전달한 기능 설명·자료를 바탕으로 WhaTap Docs에 올릴 사용자 가이드 초안을 자동 생성합니다.

**이렇게 요청하세요:**

\`\`\`
피드백/설명 없이, 최종 개선 문서 초안만 만들어줘.
\`\`\`

\`\`\`
아래 내용을 바탕으로 WhaTap Docs에 올릴 사용자 가이드 초안만 만들어줘.
\`\`\`

**Claude가 해주는 것:**
- 문서 목적·구조 정리
- UI 표기 규칙 자동 적용
- 사용자 관점 문장으로 초안 생성
- 부족한 자료는 \`[데모 링크 필요]\`, \`[화면 공유 필요]\`로 표시

---

### 최소 변경 모드 (기존 문서 보완용)

기존 문서를 전면 수정하지 않고, 의미·구조는 유지하면서 필요한 부분만 최소 범위로 개선합니다.

**이렇게 요청하세요:**

\`\`\`
기존 문서를 최대한 유지하면서, 최소 변경 모드로 개선해줘.
\`\`\`

\`\`\`
구조는 유지하고, 문장과 UI 표기만 최소 범위로 다듬어줘.
\`\`\`

**최소 변경 모드에서 Claude가 해주는 것:**
- 기존 구조·제목 최대한 유지
- 의미를 바꾸지 않는 선에서 문장 정리
- 개요 누락, UI 표기 오류 등 필수 원칙 위반만 최소 범위로 수정
- 문서 분리는 꼭 필요한 경우에만 제안
- 변경된 부분은 \`Before → After\` 형식으로 표시

## References

- \`references/ui-style-guide.md\` - UI 표기 규칙
- \`references/sentence-style-guide.md\` - 문장 스타일 규칙
- \`references/tutorial-checklist.md\` - 학습형 문서 체크리스트
- \`assets/templates/doc-template.md\` - 기본 문서 템플릿

## Author

박수빈 (WhaTap)

## License

MIT
`,
  },
  {
    name: 'jira',
    version: '3.3.0',
    description: 'Jira 통합 스킬 - 이슈 조회(/jira KEY), 생성(/jira new), 코멘트 추가',
    category: 'development',
    keywords: ["공통","skill","jira","pr-review"],
    author: {
      name: 'WhaTap Labs',
      email: 'dev@whatap.io',
    },
    homepage: 'https://github.com/whatap/claude-plugins/tree/main/plugins/jira',
    repository: 'https://github.com/whatap/claude-plugins',
    license: 'MIT',
    platform: ["macOS","Linux","Windows"],
    readme: `# Jira 통합 스킬

Jira 이슈 조회, 생성, 코멘트 추가를 지원하는 Claude Code 스킬입니다.

## Features

- \`/jira KEY\` - 이슈 상세 정보 조회 (예: \`/jira SERVER-123\`)
- \`/jira new\` - 새 이슈 생성 (대화형)
- \`/jira auto PROJECT_KEY\` - Git 작업내역 기반 이슈 자동 생성
- \`/jira comment KEY "내용"\` - 이슈에 코멘트 추가

### 조회 기능

- 이슈 상세 정보 (메타, 설명, 서브태스크, 코멘트)
- 첨부파일 자동 다운로드
- 이미지 인라인 표시 (Claude가 이미지 확인 가능)
- ADF (Atlassian Document Format) → Markdown 완전 변환

### 생성 기능

- 대화형으로 새 이슈 생성
- 담당자 미지정 시 본인으로 자동 설정
- 모든 이슈 타입에서 \`customfield_10101\` (상세 설명) 자동 설정

### Git 기반 자동 생성

- 현재 브랜치의 커밋/변경사항을 자동 분석
- WhaTap Jira 템플릿(배경, 기능 요청자, 기능 상세, 참고 사항) 자동 채움
- 사용자 확인 후 생성 (제목/내용 수정 가능)

## Prerequisites

- **Node.js 18+**: native fetch 지원 필요
- **Jira API Token**: Atlassian 계정의 API 토큰

## Installation

\`\`\`
/plugin install jira@whatap-claude-plugins
\`\`\`

## Environment Variables

\`\`\`bash
# 필수
export JIRA_EMAIL="your-email@whatap.io"
export JIRA_API_TOKEN="your-api-token"

# 선택 (기본값: https://whatap-labs.atlassian.net)
export JIRA_URL="https://your-domain.atlassian.net"
\`\`\`

### API 토큰 발급 방법

1. [Atlassian API Token 관리](https://id.atlassian.com/manage-profile/security/api-tokens) 페이지 접속
2. "Create API token" 클릭
3. 토큰 이름 입력 후 생성
4. 생성된 토큰을 \`JIRA_API_TOKEN\` 환경변수에 설정

## Usage

### 이슈 조회

\`\`\`
/jira SERVER-1448
\`\`\`

### 이슈 생성

\`\`\`
/jira new
\`\`\`

### Git 작업내역 기반 자동 생성

\`\`\`
/jira auto LOG
/jira auto FRONT 개선
\`\`\`

현재 브랜치의 git diff/log를 분석하여 Jira 템플릿에 맞는 티켓을 자동 생성합니다.
두 번째 인자로 이슈 타입 지정 가능 (기본값: 새 기능).

### 이슈에 코멘트 추가

\`\`\`
/jira comment SERVER-1448 "확인했습니다. 수정 진행하겠습니다."
\`\`\`

## Changelog

### v3.3.0

- \`/jira auto PROJECT_KEY\` 서브커맨드 추가
- Git diff/log 자동 분석으로 Jira 이슈 내용 자동 생성
- WhaTap Jira 템플릿(배경, 기능 요청자, 기능 상세, 참고 사항) 자동 채움

### v3.2.0

- \`customfield_10101\` (상세 설명) 지원을 모든 이슈 타입으로 확장 (기존: 개선 타입만)
- \`jira-update.mjs\`에서도 description 업데이트 시 \`customfield_10101\` 동시 설정

### v3.0.0

- **Breaking**: 플러그인 이름 변경 \`jira-issue\` → \`jira\`
- **Breaking**: \`/jira-new\` 스킬을 \`/jira new\` 서브커맨드로 통합
- 단일 스킬로 조회, 생성, 코멘트 모두 지원

### v2.1.0

- 이슈 생성 기능 추가 (\`/jira-new\`)
- 담당자 자동 설정

### v2.0.0

- Node.js 기반으로 완전 재작성
- 첨부파일 다운로드, 이미지 인라인 표시

### v1.0.0

- 초기 릴리스 (Bash 기반)

## License

MIT
`,
  },
  {
    name: 'jira-mcp',
    version: '1.0.0',
    description: 'MCP 기반 Jira 통합 - 환경변수 없이 OAuth로 이슈 조회/검색/생성/상태변경/코멘트',
    category: 'development',
    keywords: ["공통","skill","jira","mcp","atlassian"],
    author: {
      name: 'WhaTap Labs',
      email: 'dev@whatap.io',
    },
    homepage: 'https://github.com/whatap/claude-plugins/tree/main/plugins/jira-mcp',
    repository: 'https://github.com/whatap/claude-plugins',
    license: 'MIT',
    platform: ["macOS","Linux","Windows"],
    readme: `# Jira MCP 통합 스킬

MCP(Atlassian OAuth)를 통한 Jira 통합 스킬입니다. 환경변수 설정 없이 바로 사용 가능합니다.

## Features

- \`/jira-mcp KEY\` - 이슈 상세 조회 (ADF → 마크다운 변환)
- \`/jira-mcp search 쿼리\` - JQL 또는 텍스트 검색
- \`/jira-mcp my\` - 나에게 할당된 이슈 목록
- \`/jira-mcp my PROJECT\` - 특정 프로젝트 내 나의 이슈
- \`/jira-mcp project KEY\` - 프로젝트 최근 이슈
- \`/jira-mcp new PROJECT\` - 이슈 생성 (대화형)
- \`/jira-mcp auto PROJECT\` - Git 작업내역 기반 이슈 자동 생성
- \`/jira-mcp status KEY STATUS\` - 상태 변경
- \`/jira-mcp comment KEY "내용"\` - 코멘트 추가

## 기존 /jira 플러그인과의 차이

| | \`/jira\` (REST API) | \`/jira-mcp\` (MCP) |
|---|---|---|
| 인증 | JIRA_EMAIL + JIRA_API_TOKEN 환경변수 | MCP OAuth (설정 불필요) |
| 실행 | Node.js 스크립트 | MCP 도구 직접 호출 |
| 요구사항 | Node.js 18+, 환경변수 설정 | Atlassian MCP 연동만 |
| 첨부파일 | 다운로드 + 인라인 표시 | 미지원 |

## Prerequisites

- Claude Code에 **Atlassian MCP 연동**이 설정되어 있어야 합니다
- Node.js나 환경변수 설정은 불필요

## Installation

\`\`\`
/plugin install jira-mcp@whatap-claude-plugins
\`\`\`

## Usage

### 이슈 조회

\`\`\`
/jira-mcp LOG-655
\`\`\`

### 내 이슈 목록

\`\`\`
/jira-mcp my
/jira-mcp my LOG
\`\`\`

### 검색

\`\`\`
/jira-mcp search Log2Metric
/jira-mcp search project = LOG AND status = OPEN ORDER BY created DESC
\`\`\`

### 이슈 생성

\`\`\`
/jira-mcp new LOG
\`\`\`

### Git 기반 자동 생성

\`\`\`
/jira-mcp auto LOG
/jira-mcp auto FRONT 개선
\`\`\`

### 상태 변경

\`\`\`
/jira-mcp status LOG-655 진행중
/jira-mcp status LOG-655 Done
\`\`\`

### 코멘트 추가

\`\`\`
/jira-mcp comment LOG-655 "확인했습니다. 수정 진행하겠습니다."
\`\`\`

## WhaTap 특화

- \`customfield_10101\` (상세 설명) 자동 처리 (ADF 형식)
- WhaTap Jira 템플릿 양식 (배경, 기능 요청자, 기능 상세, 참고 사항) 자동 채움

## Changelog

### v1.0.0

- 초기 릴리스
- MCP 기반 이슈 조회, 검색, 생성, 상태 변경, 코멘트
- Git 작업내역 기반 이슈 자동 생성 (\`/jira-mcp auto\`)

## License

MIT
`,
  },
  {
    name: 'mail',
    version: '1.0.0',
    description: 'MCP 기반 Gmail 통합 - 환경변수 없이 OAuth로 메일 조회/검색/초안 작성',
    category: 'productivity',
    keywords: ["공통","skill","gmail","mcp","google"],
    author: {
      name: 'WhaTap Labs',
      email: 'dev@whatap.io',
    },
    homepage: 'https://github.com/whatap/claude-plugins/tree/main/plugins/mail',
    repository: 'https://github.com/whatap/claude-plugins',
    license: 'MIT',
    platform: ["macOS","Linux","Windows"],
    readme: `# Gmail MCP 통합 스킬

MCP(Gmail OAuth)를 통한 Gmail 통합 스킬입니다. 환경변수 설정 없이 바로 사용 가능합니다.

## Features

- \`/mail\` 또는 \`/mail inbox\` - 최근 메일 10건 조회
- \`/mail unread\` - 읽지 않은 메일
- \`/mail search 쿼리\` - Gmail 검색 구문으로 검색
- \`/mail from 이름\` - 특정 발신자 메일
- \`/mail starred\` - 별표 메일
- \`/mail read MESSAGE_ID\` - 메일 상세 조회
- \`/mail thread THREAD_ID\` - 스레드 전체 조회
- \`/mail draft\` - 초안 작성 (대화형)
- \`/mail drafts\` - 저장된 초안 목록

## Prerequisites

- Claude Code에 **Gmail MCP 연동**이 설정되어 있어야 합니다
- Node.js나 환경변수 설정은 불필요

## Installation

\`\`\`
/plugin install mail@whatap-claude-plugins
\`\`\`

## Usage

### 최근 메일

\`\`\`
/mail
/mail inbox
\`\`\`

### 읽지 않은 메일

\`\`\`
/mail unread
\`\`\`

### 메일 검색

\`\`\`
/mail search 배포
/mail search from:boss@company.com has:attachment
/mail search subject:meeting after:2026/2/1
\`\`\`

### 발신자별 조회

\`\`\`
/mail from 김철수
/mail from sender@example.com
\`\`\`

### 메일 상세/스레드 조회

\`\`\`
/mail read MESSAGE_ID
/mail thread THREAD_ID
\`\`\`

### 초안 작성

\`\`\`
/mail draft
\`\`\`

대화형으로 수신자, 제목, 본문, CC를 입력받습니다.

## 출력 형식

메일 목록은 테이블 형식으로 표시됩니다:

| # | 발신자 | 제목 | 날짜 | 읽음 |
|---|--------|------|------|------|
| 1 | 이름 \\<email\\> | 제목... | 2월 25일 | ✓/✗ |

각 메일의 \`messageId\`와 \`threadId\`가 함께 표시되어 후속 조회가 가능합니다.

## 주의사항

- **메일 발송 불가**: MCP는 초안 작성만 지원. 발송은 Gmail에서 직접 해야 합니다
- **개인정보 주의**: 메일 내용은 민감 정보를 포함할 수 있으므로 주의

## Changelog

### v1.0.0

- 초기 릴리스
- 메일 조회, 검색, 상세 보기, 스레드 보기
- 초안 작성 및 목록 조회

## License

MIT
`,
  },
  {
    name: 'mxql',
    version: '1.0.0',
    description: 'dev.whatap.io에서 MXQL 쿼리를 실행합니다. 파일, 인라인 쿼리, stdin(heredoc) 모두 지원. Chrome 쿠키 인증 사용.',
    category: 'development',
    keywords: ["dbx","skill","mxql","개발환경"],
    author: {
      name: 'WhaTap Labs',
      email: 'dev@whatap.io',
    },
    homepage: 'https://github.com/whatap/claude-plugins/tree/main/plugins/mxql',
    repository: 'https://github.com/whatap/claude-plugins',
    license: 'MIT',
    platform: ["macOS"],
    readme: `# mxql - MXQL 쿼리 실행 플러그인

dev.whatap.io의 flush API를 통해 MXQL 쿼리를 실행하는 Claude Code 스킬입니다.

## 기능

- **3가지 입력 방식 지원**
  - 파일: \`./query.mql\`
  - 인라인: \`'CATEGORY x TAGLOAD SELECT'\`
  - stdin: heredoc으로 복잡한 쿼리 입력
- Chrome 쿠키 기반 인증 (별도 로그인 불필요)
- 시간 범위 지정 옵션

## 설치

### 1. 플러그인 설치

\`\`\`bash
/plugin install mxql@whatap-claude-plugins
\`\`\`

### 2. Python venv 설정

플러그인 설치 후 최초 1회 venv를 설정해야 합니다:

\`\`\`bash
# 플러그인 디렉토리로 이동 (설치 위치 확인 필요)
cd ~/.claude/plugins/mxql/skills/mxql

# venv 생성 및 패키지 설치
python3 -m venv venv
source venv/bin/activate
pip install browser_cookie3 requests
\`\`\`

### 3. Chrome 로그인

dev.whatap.io에 Chrome으로 로그인합니다:
- URL: https://dev.whatap.io
- 계정 정보: 사내 문서 참조

## 사용법

### 파일에서 읽기

\`\`\`bash
/mxql 878 ./query.mql
\`\`\`

### 인라인 쿼리

\`\`\`bash
# 작은따옴표로 감싸기
/mxql 878 'CATEGORY db_postgresql_tables TAGLOAD SELECT LIMIT 5'
\`\`\`

### stdin (heredoc)

쌍따옴표가 많은 복잡한 쿼리에 유용:

\`\`\`bash
~/.claude/plugins/mxql/skills/mxql/run.sh 878 - <<'EOF'
CATEGORY db_postgresql_tables
FILTER oname == "dev-pg-rds"
TAGLOAD
SELECT [time, oname, tablename, total]
LIMIT 10
EOF
\`\`\`

## 입력 자동 판단

1. \`-\` → stdin에서 읽기
2. 파일이 존재하면 → 파일에서 읽기
3. 그 외 → 인라인 쿼리로 처리

## 예시 쿼리 파일

\`examples/\` 디렉토리에 샘플 쿼리가 있습니다:

- \`tagload.mql\` - 기본 TAGLOAD 쿼리
- \`filter_select.mql\` - FILTER와 SELECT 사용 예시

## 요구사항

- macOS (browser_cookie3의 Chrome 쿠키 접근)
- Python 3.8+
- Chrome 브라우저
- Dev VPN 연결

## 문제 해결

### Chrome 쿠키 접근 오류

1. Chrome이 실행 중이면 종료 후 재시도
2. Chrome에서 dev.whatap.io 로그인 상태 확인
3. Keychain Access에서 Chrome Safe Storage 접근 허용

### venv 관련 오류

\`\`\`bash
# venv 재생성
rm -rf venv
python3 -m venv venv
source venv/bin/activate
pip install browser_cookie3 requests
\`\`\`

## 라이선스

MIT
`,
  },
  {
    name: 'notification-hook',
    version: '1.0.0',
    description: '작업 완료/입력 대기 시 macOS 데스크톱 알림을 제공합니다. Claude Code가 오래 걸리는 작업을 완료하거나 사용자 입력이 필요할 때 알림을 받을 수 있습니다.',
    category: 'productivity',
    keywords: ["공통","hook","notification","macos"],
    author: {
      name: 'WhaTap Labs',
      email: 'dev@whatap.io',
    },
    homepage: 'https://github.com/whatap/claude-plugins/tree/main/plugins/notification-hook',
    repository: 'https://github.com/whatap/claude-plugins',
    license: 'MIT',
    platform: ["macOS"],
    readme: `# notification-hook

Claude Code 작업 완료/입력 대기 시 macOS 데스크톱 알림을 보내는 Hook 플러그인

## 기능

| Hook | 이벤트 | 설명 |
|------|--------|------|
| Notification | idle_prompt | 입력 대기 시 알림 |
| Notification | permission_prompt | 권한 요청 시 알림 |
| Stop | - | 작업 완료 시 알림 |
| PostToolUse | Bash (30초+) | 장시간 명령 완료 시 알림 |

## 요구사항

- macOS
- jq (\`brew install jq\`)
- terminal-notifier (권장, \`brew install terminal-notifier\`)

## 설치

### 마켓플레이스에서 설치
\`\`\`bash
# 마켓플레이스 추가
/plugin marketplace add whatap/claude-plugins

# 플러그인 설치
/plugin install notification-hook@whatap-claude-plugins
\`\`\`

### 수동 설치
\`\`\`bash
# 1. 스크립트 복사
mkdir -p ~/.claude/hooks
cp scripts/*.sh ~/.claude/hooks/
chmod +x ~/.claude/hooks/*.sh

# 2. settings.json에 Hook 추가
# ~/.claude/settings.json 또는 .claude/settings.json
\`\`\`

## 설정 예시

\`\`\`json
{
  "hooks": {
    "Notification": [
      {
        "matcher": "",
        "hooks": [
          {
            "type": "command",
            "command": "~/.claude/hooks/notify.sh"
          }
        ]
      }
    ],
    "Stop": [
      {
        "hooks": [
          {
            "type": "command",
            "command": "~/.claude/hooks/notify-stop.sh"
          }
        ]
      }
    ]
  }
}
\`\`\`

## 태그

- 공통
- hook
- notification
- macos

## 라이선스

MIT
`,
  },
  {
    name: 'skill-authoring-review',
    version: '1.1.1',
    description: 'Claude Code 스킬 작성 및 검증 도구. 새로운 스킬 초기화, 기존 스킬 검증, Anthropic 공식 가이드라인 준수 여부 확인을 지원합니다.',
    category: 'development',
    keywords: ["공통","skill","개발도구","검증"],
    author: {
      name: 'WhaTap Labs',
      email: 'dev@whatap.io',
    },
    homepage: 'https://github.com/whatap/claude-plugins/tree/main/plugins/skill-authoring-review',
    repository: 'https://github.com/whatap/claude-plugins',
    license: 'MIT',
    platform: ["macOS","Linux","Windows"],
    readme: `# Skill Authoring & Review

Claude Code 스킬 작성 및 검증 도구입니다. Anthropic 공식 가이드라인을 기반으로 합니다.

## Features

- 새로운 스킬 초기화 (디렉토리 구조 + 템플릿)
- 기존 스킬 검증 (구조, frontmatter, 스타일)
- 일괄 검증 지원 (recursive)
- 다양한 출력 형식 (text, json, markdown)

## Prerequisites

- **Python 3.9+**: 검증 스크립트 실행용
- **Bash**: 초기화 스크립트 실행용

## Installation

Claude Code에서 플러그인을 설치하면 자동으로 스킬을 사용할 수 있습니다.

## Usage

### 새 스킬 생성

\`\`\`bash
# 기본 사용법
~/.claude/skills/skill-authoring-review/scripts/init_skill.sh <skill-name> <output-directory>

# 예시
~/.claude/skills/skill-authoring-review/scripts/init_skill.sh pdf-editor ~/.claude/skills
\`\`\`

생성되는 구조:
\`\`\`
<skill-name>/
├── SKILL.md          # 메인 스킬 문서 (편집 필요)
├── scripts/          # 실행 스크립트
│   └── example.sh
├── references/       # 참조 문서
│   └── documentation.md
└── assets/           # 출력 파일용 리소스
\`\`\`

### 스킬 검증

\`\`\`bash
# 단일 스킬 검증
python3 ~/.claude/skills/skill-authoring-review/scripts/validate_skill.py ~/.claude/skills/my-skill

# 전체 스킬 검증 (재귀)
python3 ~/.claude/skills/skill-authoring-review/scripts/validate_skill.py ~/.claude/skills --recursive

# JSON 출력
python3 ~/.claude/skills/skill-authoring-review/scripts/validate_skill.py ~/.claude/skills --format json

# Markdown 리포트
python3 ~/.claude/skills/skill-authoring-review/scripts/validate_skill.py ~/.claude/skills --format markdown
\`\`\`

### 출력 예시

\`\`\`
============================================================
Skill: my-skill
Path: /Users/user/.claude/skills/my-skill
Words: 1234
Valid: Yes
============================================================

  WARNINGS:
    - [body] Found 3 second-person usage(s)
      Suggestion: Use imperative/infinitive form. Examples: L45: 'You can configure...'

  SUGGESTIONS:
    - [progressive_disclosure] SKILL.md is 1234 words (recommended: 1,500-2,000)
      Suggestion: Consider splitting into references/ if content grows
\`\`\`

## Validation Rules

### Critical (필수 수정)
- \`SKILL.md\` 파일 존재 (대문자)
- frontmatter의 \`name\` 필드
- frontmatter의 \`description\` 필드

### Warning (권장 수정)
- 디렉토리 이름과 \`name\` 필드 일치
- description 3인칭 작성
- body에서 2인칭 사용 금지 (you, your)

### Suggestion (개선 권장)
- 적정 분량: 1,500-2,000 words
- 트리거 조건 명시

## Skill Guidelines Summary

### Frontmatter 예시

\`\`\`yaml
---
name: my-skill
description: Brief description in third-person. This skill should be used when [conditions]. Triggers on requests like "[phrases]".
---
\`\`\`

### 작성 스타일

**올바른 예:**
\`\`\`markdown
To rotate a PDF, run the following command:
\`\`\`

**잘못된 예:**
\`\`\`markdown
You can rotate a PDF by running:
\`\`\`

## References

- \`references/anthropic-skill-guide.md\` - Anthropic 공식 가이드라인 요약
- \`references/validation-checklist.md\` - 상세 검증 체크리스트
- \`references/templates.md\` - 스킬 유형별 템플릿
- \`assets/minimal-skill.md\` - 최소 유효 스킬 예시

## License

MIT
`,
  },
  {
    name: 'slack-cdp',
    version: '1.0.0',
    description: 'Slack 데스크톱 앱 CDP 제어 - 슬래시 커맨드 실행, 채널 이동 자동화',
    category: 'infrastructure',
    keywords: ["공통","인프라","slack","cdp","자동화"],
    author: {
      name: 'WhaTap Labs',
      email: 'dev@whatap.io',
    },
    homepage: 'https://github.com/whatap/claude-plugins/tree/main/plugins/slack-cdp',
    repository: 'https://github.com/whatap/claude-plugins',
    license: 'MIT',
    platform: ["macOS"],
    readme: `# slack-cdp

Slack 데스크톱 앱을 CDP(Chrome DevTools Protocol)로 제어하는 공유 인프라 플러그인.

## 기능

- Slack 슬래시 커맨드 프로그래밍적 실행
- 채널 이동 (Cmd+K Quick Switcher)
- 메시지 입력창 제어

## 사용법

### CDP 연결 확인/시작
\`\`\`bash
bash plugins/slack-cdp/scripts/ensure-slack-cdp.sh [port]
# 기본 포트: 9333
\`\`\`

### 슬래시 커맨드 실행
\`\`\`bash
NODE_PATH=plugins/slack-cdp/node_modules \\
  node plugins/slack-cdp/scripts/slack-command.js \\
  --channel "채널명" \\
  --command "/커맨드" \\
  --text "파라미터"
\`\`\`

## 전제조건

- Slack 데스크톱 앱이 CDP 모드로 실행 필요
- \`npm install\` 실행 (puppeteer-core)

## Slack CDP 모드 시작

\`\`\`bash
# 자동 (스크립트가 처리)
bash scripts/ensure-slack-cdp.sh

# 수동
osascript -e 'quit app "Slack"' && sleep 2 && open -a "Slack" --args --remote-debugging-port=9333
\`\`\`
`,
  },
  {
    name: 'tagcount',
    version: '1.0.0',
    description: 'dev.whatap.io에서 MXQL TAGLOAD 쿼리를 실행하여 카테고리의 tag와 field를 조회합니다. Chrome 쿠키 인증을 사용합니다.',
    category: 'development',
    keywords: ["dbx","skill","mxql","개발환경"],
    author: {
      name: 'WhaTap Labs',
      email: 'dev@whatap.io',
    },
    homepage: 'https://github.com/whatap/claude-plugins/tree/main/plugins/tagcount',
    repository: 'https://github.com/whatap/claude-plugins',
    license: 'MIT',
    platform: ["macOS"],
    readme: `# tagcount - MXQL Tag/Field 조회 플러그인

dev.whatap.io의 flush API를 통해 MXQL TAGLOAD 쿼리를 실행하여 카테고리의 tag와 field를 확인하는 Claude Code 스킬입니다.

## 기능

- MXQL TAGLOAD 쿼리 자동 생성 및 실행
- Chrome 쿠키 기반 인증 (별도 로그인 불필요)
- tag/field 자동 분류
- 샘플 데이터 표시

## 설치

### 1. 플러그인 설치

\`\`\`bash
/plugin install tagcount@whatap-claude-plugins
\`\`\`

### 2. Python venv 설정

플러그인 설치 후 최초 1회 venv를 설정해야 합니다:

\`\`\`bash
# 플러그인 디렉토리로 이동 (설치 위치 확인 필요)
cd ~/.claude/plugins/tagcount/skills/tagcount

# venv 생성 및 패키지 설치
python3 -m venv venv
source venv/bin/activate
pip install browser_cookie3 requests
\`\`\`

### 3. Chrome 로그인

dev.whatap.io에 Chrome으로 로그인합니다:
- URL: https://dev.whatap.io
- 계정 정보: 사내 문서 참조

## 사용법

\`\`\`bash
# Claude Code에서
/tagcount 878 db_postgresql_tables

# MySQL 테이블
/tagcount 1627 db_mysql_tables

# Oracle 세션
/tagcount 123 db_oracle_session
\`\`\`

## 출력 예시

\`\`\`json
{
  "tags": ["pname", "oname", "datname", "schemaname", "tablename"],
  "fields": ["table", "index", "total"],
  "sample_data": {
    "time": 1770024025000,
    "pcode": 878,
    "pname": "postgres-v2-test",
    "oname": "dev-pg-rds",
    "datname": "db1",
    "schemaname": "public",
    "tablename": "kwlee",
    "table": 40960,
    "index": 0,
    "total": 40960,
    "oid": 78064568
  }
}
\`\`\`

## 요구사항

- macOS (browser_cookie3의 Chrome 쿠키 접근)
- Python 3.8+
- Chrome 브라우저
- Dev VPN 연결

## 문제 해결

### Chrome 쿠키 접근 오류

1. Chrome이 실행 중이면 종료 후 재시도
2. Chrome에서 dev.whatap.io 로그인 상태 확인
3. Keychain Access에서 Chrome Safe Storage 접근 허용

### venv 관련 오류

\`\`\`bash
# venv 재생성
rm -rf venv
python3 -m venv venv
source venv/bin/activate
pip install browser_cookie3 requests
\`\`\`

## 라이선스

MIT
`,
  },
  {
    name: 'usage-statusbar',
    version: '1.1.0',
    description: 'Context Window 사용량과 5시간 블록 사용량을 이모지 바 그래프로 statusline에 표시합니다.',
    category: 'productivity',
    keywords: ["공통","statusline","usage","모니터링"],
    author: {
      name: 'WhaTap Labs',
      email: 'dev@whatap.io',
    },
    homepage: 'https://github.com/whatap/claude-plugins/tree/main/plugins/usage-statusbar',
    repository: 'https://github.com/whatap/claude-plugins',
    license: 'MIT',
    platform: ["macOS","Linux","Windows"],
    readme: `# usage-statusbar

Claude Code statusline 플러그인으로 Context Window와 5시간 블록 사용량을 이모지 막대 그래프로 표시합니다.

## 출력 예시

\`\`\`
🧠 🟩🟩🟩🟩🟩⬜⬜⬜⬜⬜ 46% | ⏰ 🟩⬜⬜⬜⬜⬜⬜⬜⬜⬜ 8% | Reset: 4h 49m
\`\`\`

## 기능

| 항목 | 설명 | 데이터 소스 |
|------|------|------------|
| 🧠 Context | 현재 컨텍스트 윈도우 사용량 | stdin JSON (\`used_percentage\`) |
| ⏰ Block | 5시간 블록 사용량 | Anthropic API (\`utilization\`) |
| Reset | 블록 리셋까지 남은 시간 | Anthropic API (\`resets_at\`) |

## 색상 구간

| 범위 | 색상 |
|------|------|
| 0-50% | 🟩 녹색 |
| 51-80% | 🟨 노란색 |
| 81-100% | 🟥 빨간색 |
| 빈 칸 | ⬜ 흰색 |

## 설치

### 1. 마켓플레이스에서 설치

\`\`\`bash
claude plugins add usage-statusbar
\`\`\`

### 2. 의존성 설치

\`\`\`bash
cd ~/.claude/plugins/usage-statusbar
bun install
\`\`\`

> **참고**: \`dist/index.js\`는 사전 빌드되어 포함되어 있습니다. 소스 수정 시에만 \`bun run build\`를 실행하세요.

### 3. statusLine 설정 (수동 필요)

> **왜 수동 설정이 필요한가요?**
>
> \`statusLine\`은 Claude Code에서 **한 번에 하나만 활성화**할 수 있습니다. 여러 플러그인이 statusLine을 제공할 수 있기 때문에, 어떤 것을 사용할지는 사용자가 명시적으로 선택해야 합니다.
>
> | 플러그인 유형 | 자동 적용 | 비고 |
> |-------------|----------|------|
> | hooks | ✅ | hooks.json 자동 병합 |
> | commands | ✅ | 명령어 자동 등록 |
> | statusLine | ❌ | 사용자 선택 필요 |

#### 방법 A: Claude Code에 요청하기

Claude Code 세션에서 다음과 같이 요청하면 자동으로 설정해줍니다:

\`\`\`
usage-statusbar 플러그인의 statusLine을 설정해줘
\`\`\`

또는:

\`\`\`
/statusline-setup usage-statusbar
\`\`\`

#### 방법 B: 직접 설정하기

\`~/.claude/settings.json\` (전역) 또는 프로젝트의 \`.claude/settings.json\`에 추가:

\`\`\`json
{
  "statusLine": {
    "type": "command",
    "command": "bun ~/.claude/plugins/usage-statusbar/dist/index.js",
    "padding": 0
  }
}
\`\`\`

> **참고**: 경로는 실제 플러그인 설치 위치에 맞게 수정하세요.

## 요구사항

- **Bun**: TypeScript 런타임
- **Claude Code 로그인**: OAuth 인증 필요

### 플랫폼별 credential 접근

| 플랫폼 | 방식 |
|--------|------|
| macOS | Keychain (\`security find-generic-password\`) |
| Linux / Windows (WSL) | \`~/.claude/.credentials.json\` 파일 |

## 작동 방식

1. stdin에서 Claude Code가 전달하는 JSON 읽기 (context window 정보)
2. 파일 캐시 확인 (\`~/.claude/.usage-cache.json\`, TTL 60초)
   - 캐시 히트 → API 호출 생략, 캐시 데이터 사용
   - 캐시 미스 → OAuth 토큰 가져오기 → API 호출 → 캐시 갱신
3. Anthropic API (\`/api/oauth/usage\`) 호출하여 5시간 블록 정보 조회
4. 이모지 막대 그래프로 렌더링하여 stdout 출력

### 캐싱

statusline 커맨드는 Claude Code가 **매 렌더 사이클마다 실행**합니다.
캐싱 없이 매번 API를 호출하면 rate limit(429)에 걸려 usage 정보가 표시되지 않습니다.

| 항목 | 값 |
|------|-----|
| 캐시 파일 | \`~/.claude/.usage-cache.json\` |
| TTL | 60초 |
| 방식 | 파일 기반 (프로세스가 매번 새로 뜨므로 인메모리 불가) |
| 실패 처리 | 캐시 읽기/쓰기 실패 시 무시 (best-effort) |

범용 캐시 유틸(\`cache-utils.ts\`)은 다른 statusline 플러그인에서도 재사용 가능합니다.

## API 응답 예시

\`\`\`json
{
  "five_hour": {
    "utilization": 8.0,
    "resets_at": "2026-02-04T05:59:59.564221+00:00"
  },
  "seven_day": {
    "utilization": 53.0,
    "resets_at": "2026-02-05T09:59:59.564247+00:00"
  }
}
\`\`\`

## 라이선스

MIT
`,
  },
  {
    name: 'who',
    version: '2.0.0',
    description: '팀원 부재/휴가/외근 조회 - Google Calendar 연동 (/who)',
    category: 'development',
    keywords: ["공통","skill","calendar","attendance","vacation"],
    author: {
      name: 'WhaTap Labs',
      email: 'dev@whatap.io',
    },
    homepage: 'https://github.com/whatap/claude-plugins/tree/main/plugins/who',
    repository: 'https://github.com/whatap/claude-plugins',
    license: 'MIT',
    platform: ["macOS","Linux","Windows"],
    readme: `# who - 팀원 부재/휴가/외근/팀 구성원/일정 조회

Google Calendar 연동으로 팀원의 휴가, 외근, 미팅 일정을 조회하고, Flex 조직도 기반 팀 구성원을 확인하는 Claude Code 스킬입니다.

## 기능

- 특정 팀원의 오늘/특정일/이번 주/기간별 부재 조회
- 전체 부재자 목록 조회
- 휴가 종류 구분 (연차, 반차, 반반차, 공가, 경조)
- 외근 일정 (CRE/CSM) 조회
- **팀 구성원 조회** — Flex 조직도 기반 팀/셀 단위 구성원 확인
- **개인 일정 조회** — 미팅 일정 포함 조회 (Apps Script 배포 필요)

## Installation

\`\`\`bash
claude install-plugin github:whatap/claude-plugins/plugins/who
\`\`\`

## Usage / 사용법

### 부재 조회

\`\`\`
/who 이헌섭              # 오늘 부재 확인
/who 이헌섭 이번주       # 이번 주 부재 확인
/who 이헌섭 2026-02-14   # 특정일 확인
/who all                 # 오늘 전체 부재자
/who all 이번주          # 이번 주 전체 부재자
\`\`\`

### 팀 조회

\`\`\`
/who teams               # 전체 팀 목록
/who Platform팀          # 팀 구성원 + 부재 현황
/who 플랫폼팀            # 별칭으로도 조회 가능
\`\`\`

### 개인 일정 조회

\`\`\`
/who 이헌섭 일정         # 오늘 부재 + 미팅 일정
/who 이헌섭 이번주 일정  # 이번 주 부재 + 미팅 일정
\`\`\`

## 아키텍처

\`\`\`
Claude Code Skill (/who)
  ├── who-fetch.mjs (Node.js)
  │   → Google Apps Script Web App (HTTPS GET)
  │   → Google Calendar API
  │   → JSON 응답 (부재 + 일정)
  │
  ├── flex-fetch.mjs (Node.js)
  │   → team-data.json (Flex 조직도 수동 추출)
  │   → JSON 응답 (팀 구조 + 구성원)
  │
  └── Claude가 결과 병합/포맷팅하여 표시
\`\`\`

## 캘린더 소스

| 캘린더 | 용도 |
|--------|------|
| 휴가 캘린더 | 연차, 반차, 반반차, 공가, 경조 |
| CRE 외근 캘린더 | CRE팀 외근 일정 |
| CSM 외근 캘린더 | CSM팀 외근 일정 |

## 팀 데이터 관리

팀 구성원 데이터는 \`team-data.json\`에 정적으로 관리됩니다.

- **소스**: Flex (flex.team) 조직도에서 수동 추출
- **업데이트**: 조직 변경 시 \`team-data.json\`을 직접 수정
- **이유**: Flex API가 비공식(쿠키 인증)이라 자동화 불가

### 개인 일정 조회 설정

개인 캘린더 일정 조회는 Google Apps Script에 \`mode=schedule\` 핸들러가 필요합니다.
배포 전까지는 부재 정보만 반환됩니다.
`,
  }
]

export function getPluginByName(name: string): Plugin | undefined {
  return plugins.find((p) => p.name === name)
}

export function searchPlugins(query: string, category?: string, tags?: string[]): Plugin[] {
  return plugins.filter((plugin) => {
    // Search query
    if (query) {
      const q = query.toLowerCase()
      const matchesQuery =
        plugin.name.toLowerCase().includes(q) ||
        plugin.description.toLowerCase().includes(q) ||
        plugin.keywords.some((k) => k.toLowerCase().includes(q))
      if (!matchesQuery) return false
    }

    // Category filter
    if (category && category !== 'all' && plugin.category !== category) {
      return false
    }

    // Tags filter
    if (tags && tags.length > 0) {
      const hasTag = tags.some((tag) =>
        plugin.keywords.some((k) => k.toLowerCase() === tag.toLowerCase())
      )
      if (!hasTag) return false
    }

    return true
  })
}
